package com.softsalud.software.login;

import com.softsalud.software.controller.resource.FileProperties;
import javax.swing.JOptionPane;

/**
 * Esta clase hace de login del sistema
 *
 * @author Gonzalez Ismael
 */
public class JFrameLogin extends javax.swing.JFrame {

    private final FileProperties properties;
    private final LoginListener loginListener;

    private static final int EXITO = 11;
    private static final int ERROR_USER = 33;
    private static final int ERROR_PASSWORD = 55;
    private static final int ERROR_BOTH = 77;

    /**
     * Creates new form JFrameLogin
     *
     * @param loginListener
     */
    public JFrameLogin(LoginListener loginListener) {
        this.loginListener = loginListener;
        initComponents();
        properties = new FileProperties();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabelUser.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUser.setText("USUARIO :");

        jLabelPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPassword.setText("CONTRASEÑA :");

        btnIniciarSesion.setText("INICIAR SESIÓN");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jPasswordField.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabelPassword))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelUser)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUser)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUser))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        switch (validarUsuarioContraseña()) {
            case EXITO -> {
                mostrarExito();
                if (loginListener != null) {
                    loginListener.onLoginSuccess();
                }
                dispose();
            }
            case ERROR_USER ->
                mostrarError("El usuario no coincide, intente nuevamente.");
            case ERROR_PASSWORD ->
                mostrarError("La contraseña no coincide, intente nuevamente.");
            case ERROR_BOTH ->
                mostrarError("Ambos datos ingresados son incorrectos, intente nuevamente.");
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private int validarUsuarioContraseña() {
        String usuarioFile = properties.getFile().getProperty("usuarioSS");
        String contraseñaFile = properties.getFile().getProperty("contraseñaSS");
        String usuarioField = jTextFieldUser.getText();
        String contraseñaField = new String(jPasswordField.getPassword());
        if (!usuarioFile.equals(usuarioField) && !contraseñaFile.equals(contraseñaField)) {
            return ERROR_BOTH;
        } else if (!usuarioFile.equals(usuarioField)) {
            return ERROR_USER;
        } else if (!contraseñaFile.equals(contraseñaField)) {
            return ERROR_PASSWORD;
        } else {
            return EXITO;
        }
    }

    private void mostrarError(String mensaje) {
        String titulo = "Error";
        int tipoMensaje = JOptionPane.ERROR_MESSAGE;
        JOptionPane.showMessageDialog(this, mensaje, titulo, tipoMensaje);
    }

    private void mostrarExito() {
        String mensaje = "Bienvenido";
        String titulo = "Inicio de sesión exitoso";
        int tipoMensaje = JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(this, mensaje, titulo, tipoMensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
