package com.softsalud.software.view;

import com.softsalud.software.controller.ReporteController;
import static com.softsalud.software.view.validation.VistaValidacion.tieneContenido;
import static com.softsalud.software.view.validation.VistaValidacion.validarNombreArchivo;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ismael
 */
public class JDialogReporte extends javax.swing.JDialog {

    private final ReporteController controller;
    private final int CARNET = 0, ALLPERSON = 1, ALLVACCINE = 2, PERSONPERVACCINE = 3;

    /**
     * Creates new form JDialogReport
     *
     * @param parent
     * @param modal
     * @param controller
     */
    public JDialogReporte(java.awt.Frame parent, boolean modal, ReporteController controller) {
        super(parent, modal);
        initComponents();
        this.controller = controller;
        seleccionarOpcionEventoItemListenner();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlSubTitulo = new javax.swing.JLabel();
        jtfFileName = new javax.swing.JTextField();
        jtfParam = new javax.swing.JTextField();
        jlParam = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        btnGenerarReporte = new javax.swing.JButton();
        jcbOpcionesReportes = new javax.swing.JComboBox<>();
        jlFileName = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jcbExtension = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Generador de Informes Multi-Formato");

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("para obtener análisis y datos precisos con flexibilidad y facilidad.");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cree informes detallados en diversos formatos, como PDF, Excel y más, ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlSubTitulo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jlSubTitulo.setForeground(new java.awt.Color(44, 62, 80));
        jlSubTitulo.setText("Generar Carnet de Vacunación : ");

        jtfFileName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFileNameKeyTyped(evt);
            }
        });

        jlParam.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlParam.setForeground(new java.awt.Color(44, 62, 80));
        jlParam.setText("DNI Persona : ");

        jTextArea.setEditable(false);
        jTextArea.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jTextArea.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea.setLineWrap(true);
        jTextArea.setRows(1);
        jTextArea.setTabSize(1);
        jTextArea.setText("\n        \t\tSeleccione el reporte que desee generar, luego ingrese el \n  \t\t\t\t\tnombre de su archivo y, por último, presionar en\n                      botón al costado para generar el documento.");
        jTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea);

        btnGenerarReporte.setText("Generar");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        jcbOpcionesReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnet de Vacunación", "Todas las personas que hay en el sistema", "Todas las vacunas que hay en el sistema", "Las personas que se aplicaron una vacuna" }));

        jlFileName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlFileName.setForeground(new java.awt.Color(44, 62, 80));
        jlFileName.setText("Nombre del Archivo : ");

        btnHelp.setBackground(new java.awt.Color(255, 255, 255));
        btnHelp.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(0, 0, 204));
        btnHelp.setText("?");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerarReporte))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlFileName)
                                    .addComponent(jlParam, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfParam)
                                    .addComponent(jtfFileName)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlSubTitulo)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jcbOpcionesReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnHelp)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbOpcionesReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlParam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtfFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFileName))
                .addGap(18, 18, 18)
                .addComponent(btnGenerarReporte)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jcbExtension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pdf", "html", "xls" }));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Seleccione el tipo de archivo al cual quiere exportar su informacion:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        String nombreArchivo = jtfFileName.getText();
        String parametro = jtfParam.getText();
        String seleccionExtension = jcbExtension.getSelectedItem().toString();
        int opcionElegida = jcbOpcionesReportes.getSelectedIndex();
        if (sonDatosValidos(nombreArchivo, parametro, opcionElegida)) {
            String urlReporte = seGeneroReporteSeleccionado(nombreArchivo, parametro, seleccionExtension);
            mostrarMensajeConResultado(urlReporte);
            abrirArchivo(urlReporte);
        } else {
            mostrarMensajeDatosInvalidos();
        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void jtfFileNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFileNameKeyTyped
        validarNombreArchivo(evt);
    }//GEN-LAST:event_jtfFileNameKeyTyped

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        String mensaje = "Solo complete los campos y presione 'Generar' para crear el reporte.\nEn caso de dudas observe el manual de usuario\nen el menú Ayuda en el menú Principal.";
        JOptionPane.showMessageDialog(null, mensaje, "Asistente", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void seleccionarOpcionEventoItemListenner() {
        jcbOpcionesReportes.addActionListener((ActionEvent e) -> {
            switch (jcbOpcionesReportes.getSelectedIndex()) {
                case CARNET -> {
                    jlSubTitulo.setText("Generar Carnet de Vacunación : ");
                    jlParam.setVisible(true);
                    jlParam.setText("DNI Persona : ");
                    jtfParam.setVisible(true);
                    jtfParam.setText("");
                }
                case ALLPERSON -> {
                    jlSubTitulo.setText("Generar Reporte con Todas las Personas : ");
                    jlParam.setVisible(false);
                    jtfParam.setVisible(false);
                }
                case ALLVACCINE -> {
                    jlSubTitulo.setText("Generar Reporte con Todas las Vacunas : ");
                    jlParam.setVisible(false);
                    jtfParam.setVisible(false);
                }
                case PERSONPERVACCINE -> {
                    jlSubTitulo.setText("Reportar todas las personas que se vacunaron con : ");
                    jlParam.setVisible(true);
                    jlParam.setText("Marca Vacuna : ");
                    jtfParam.setVisible(true);
                    jtfParam.setText("");
                }
            }
        });
    }

    private boolean sonDatosValidos(String nombreArchivo, String parametro, int opcionElegida) {
        return switch (opcionElegida) {
            case CARNET ->
                tieneContenido(nombreArchivo) && tieneContenido(parametro) && existePersona(parametro);
            case PERSONPERVACCINE ->
                tieneContenido(nombreArchivo) && tieneContenido(parametro) && existeVacuna(parametro);
            default ->
                tieneContenido(nombreArchivo);
        };
    }

    private String seGeneroReporteSeleccionado(String nombreArchivo, String parametro, String seleccionExtension) {
        switch (jcbOpcionesReportes.getSelectedIndex()) {
            case CARNET -> {
                return controller.generarCarnetVacunacion(nombreArchivo, parametro, seleccionExtension);
            }
            case ALLPERSON -> {
                return controller.generarReportePersonas(nombreArchivo, seleccionExtension);
            }
            case ALLVACCINE -> {
                return controller.generarReporteVacunas(nombreArchivo, seleccionExtension);
            }
            case PERSONPERVACCINE -> {
                return controller.generarReportePersonasPorVacuna(parametro, nombreArchivo, seleccionExtension);
            }
        }
        return null;
    }

    private void mostrarMensajeConResultado(String seGenero) {
        if (seGenero != null) {
            JOptionPane.showMessageDialog(null, "Copia guardada correctamente.", "Todo Correcto", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Fallo la generación.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarMensajeDatosInvalidos() {
        String mensaje = "Faltan ingresar datos. Revise e intente de nuevo.";
        String titulo = "Error";
        int tipoMensaje = JOptionPane.ERROR_MESSAGE;
        JOptionPane.showMessageDialog(rootPane, mensaje, titulo, tipoMensaje);
    }

    private void abrirArchivo(String urlReporte) {
        File archivo = new File(urlReporte);
        try {
            // Verificar si el sistema soporta el escritorio
            if (Desktop.isDesktopSupported()) {
                // Obtener la instancia del escritorio
                Desktop escritorio = Desktop.getDesktop();

                // Abrir el archivo con la aplicación predeterminada
                escritorio.open(archivo);
            } else {
                System.out.println("El escritorio no está soportado en este sistema.");
            }
        } catch (IOException e) {
            System.out.println("Error al abrir el archivo: " + e.getMessage());
        }
    }

    private boolean existeVacuna(String vacuna) {
        return controller.existeVacuna(vacuna);
    }

    private boolean existePersona(String dni) {
        return controller.existePersona(Long.valueOf(dni));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JComboBox<String> jcbExtension;
    private javax.swing.JComboBox<String> jcbOpcionesReportes;
    private javax.swing.JLabel jlFileName;
    private javax.swing.JLabel jlParam;
    private javax.swing.JLabel jlSubTitulo;
    private javax.swing.JTextField jtfFileName;
    private javax.swing.JTextField jtfParam;
    // End of variables declaration//GEN-END:variables
}
