package com.softsalud.software.view;

import com.softsalud.software.controller.resource.FileProperties;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Gonzalez Ismael
 */
public class JDialogConfig extends javax.swing.JDialog {

    private final FileProperties fileProperties;
    private final JFileChooser seleccionArchivo;

    /**
     * Creates new form JDialogConfig
     *
     * @param parent
     * @param modal
     */
    public JDialogConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.fileProperties = new FileProperties();
        this.seleccionArchivo = new JFileChooser();
        actualizarContenidoJtextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtfBackup = new javax.swing.JTextField();
        jtfOutputFiles = new javax.swing.JTextField();
        btnChangeBackupLocation = new javax.swing.JButton();
        btnChangeOutputReportsLocation = new javax.swing.JButton();
        btnRestablecerPredeterminados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Configurar la Ubicación de las Carpetas");

        jtfBackup.setText(" ");
        jtfBackup.setEnabled(false);

        jtfOutputFiles.setText(" ");
        jtfOutputFiles.setEnabled(false);

        btnChangeBackupLocation.setText("Cambiar Backup");
        btnChangeBackupLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeBackupLocationActionPerformed(evt);
            }
        });

        btnChangeOutputReportsLocation.setText("Cambiar Reportes");
        btnChangeOutputReportsLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeOutputReportsLocationActionPerformed(evt);
            }
        });

        btnRestablecerPredeterminados.setText("Restablecer Predeterminados");
        btnRestablecerPredeterminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerPredeterminadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnChangeBackupLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBackup))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnChangeOutputReportsLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfOutputFiles))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRestablecerPredeterminados)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangeBackupLocation)
                    .addComponent(jtfBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangeOutputReportsLocation)
                    .addComponent(jtfOutputFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestablecerPredeterminados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeBackupLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeBackupLocationActionPerformed
        if (iniciarExploradorArchivos("urlBackupLocation") == JFileChooser.APPROVE_OPTION) {
            File selectedDirectory = seleccionArchivo.getSelectedFile(); // Obtiene el directorio seleccionado
            String ubicacion = selectedDirectory.getAbsolutePath(); // Obtiene la ruta absoluta del directorio seleccionado
            fileProperties.getFile().setProperty("urlBackupLocation", ubicacion);
            fileProperties.saveFile();
            actualizarContenidoJtextFields();
        }
    }//GEN-LAST:event_btnChangeBackupLocationActionPerformed

    private void btnChangeOutputReportsLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeOutputReportsLocationActionPerformed
        if (iniciarExploradorArchivos("urlOutputLocation") == JFileChooser.APPROVE_OPTION) {
            File selectedDirectory = seleccionArchivo.getSelectedFile(); // Obtiene el directorio seleccionado
            String ubicacion = selectedDirectory.getAbsolutePath(); // Obtiene la ruta absoluta del directorio seleccionado
            fileProperties.getFile().setProperty("urlOutputLocation", ubicacion);
            fileProperties.saveFile();
            actualizarContenidoJtextFields();
        }
    }//GEN-LAST:event_btnChangeOutputReportsLocationActionPerformed

    private void btnRestablecerPredeterminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerPredeterminadosActionPerformed
        fileProperties.getFile().setProperty("urlBackupLocation", "C:/ProgramData/Backups");
        String nombreDeUsuario = System.getProperty("user.name");
        fileProperties.getFile().setProperty("urlOutputLocation", "C:/Users/" + nombreDeUsuario + "/Documents/Reportes de Salud");
        fileProperties.saveFile();
        actualizarContenidoJtextFields();
    }//GEN-LAST:event_btnRestablecerPredeterminadosActionPerformed

    private void actualizarContenidoJtextFields() {
        jtfBackup.setText(fileProperties.getFile().getProperty("urlBackupLocation"));
        jtfOutputFiles.setText(fileProperties.getFile().getProperty("urlOutputLocation"));
    }

    private int iniciarExploradorArchivos(String key) {
        String rutaDefault = fileProperties.getFile().getProperty(key);
        File directorioInicial = new File(rutaDefault);
        seleccionArchivo.setCurrentDirectory(directorioInicial);
        seleccionArchivo.setDialogTitle("Seleccione una ubicación de respaldo");
        seleccionArchivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // Solo permite seleccionar directorios
        return seleccionArchivo.showOpenDialog(this);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeBackupLocation;
    private javax.swing.JButton btnChangeOutputReportsLocation;
    private javax.swing.JButton btnRestablecerPredeterminados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtfBackup;
    private javax.swing.JTextField jtfOutputFiles;
    // End of variables declaration//GEN-END:variables
}
